version: 2.1
jobs:
  lint:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: pip install -r requirements-dev.txt
      - run: black --check .

  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: pytest

workflows:
  version: 2
  quality-and-tests:
    jobs:
      - lint
      - test
